### ISSUE TITLE
[Release] v1.0.0

### ISSUE THREAD

**Issue by Luthetus** [Luthetus/Luthetus.Ide#123]
Here I will keep a list of all that I aim to finish for the v1.0.0 release.

- 0 warnings
- Version Control System integration
- Diff Editor
- Unit tests for regression testing
- C# Compiler Service provides every feature that Visual Studio has at minimum
- Debugging
- Unit Test explorer/runner
- Never freezes
- Polymorphic UI (An  opened file in the text editor results in a tab being shown. Therefore, I should be able to click and drag that tab off from the editor and have it turn  into a dialog. Then I can take any dialog, and drag and drop it into any related dropzone. Example, a text editor that was made into a dialog should be draggable into the editor to make a tab)
- Complete Grid Functionality (Any polymorphic UI element) should be able to be dragged around, this then shows a dropzone north-east-south-west and one center. This lets user make arbitrary amount of columns or rows in the grid. Or create tabs within a panel as they want.
- Multi-cursor
- Multi-select tree view
- Text Editor: add collapsible rows
- Text Editor: track the current level of indentation. When one hits newline, insert onto the newline the current level of indentation. Create markers for indentation. Perhaps this is to mean an open curly brace raises indentation level and then a closing curly brace decreases indentation level. Then this can be tracked.
- Format file
- I found a comment I made, it seems like a good idea: "/// TODO: Short circuit record value comparison by learning the order that values are compared, then put something obvious as the first comparison. (2023-09-11)"

If I get ideas about an entry in the previous bulleted list I'll make a respective note after this point.

### 0 warnings
I have a branch where I am making these changes.
### Version Control System integration
I will start with git, then make an interface abstraction from there.
### Diff Editor
[Longest common subsequence calculation progress](https://github.com/Luthetus/Luthetus.Ide/blob/main/Luthetus.TextEditor/Source/Lib/Luthetus.TextEditor.RazorLib/Diffs/Models/TextEditorDiffResult.cs)
### Unit tests for regression testing
A lot of the UI won't be part of my focus here. More so, manipulating a text editor through C# itself and ensuring results are asserted.
### C# Compiler Service provides every feature that Visual Studio has at minimum
[CSharpCompilerService.cs](https://github.com/Luthetus/Luthetus.Ide/blob/main/Luthetus.CompilerServices/Source/CSharp/Source/CompilerServiceCase/CSharpCompilerService.cs).
A big issue with the current code (2023-11-1) is that namespaces are being pulled into scope multiple times causing classes to appear multiple times when the Binder provides auto-complete.
Also, things I'm calling [AmbiguousIdentifierNode.cs](https://github.com/Luthetus/Luthetus.Ide/blob/main/Luthetus.TextEditor/Source/Lib/Luthetus.TextEditor.RazorLib/CompilerServices/Syntax/SyntaxNodes/AmbiguousIdentifierNode.cs).
So, one is parsing a method definition. If the return type of the method is not a Type within the scope. It results in this type/namespace possible state and its something I'm working out.
### Debugging
[netcoredbg](https://github.com/Samsung/netcoredbg)
I need to look into how debugging works. I was provided a link to this open source dotnet debugger on reddit at one point. So I'll look further into that as well.
### Unit Test explorer/runner
How does one discover unit tests? The ideas in my head at this moment are (2023-11-1):
- Does dotnet CLI discover unit tests?
- C# Compiler Service can be used to find the XUnit attribute usage? Then, how does one implement arbitrary testing frameworks.
- In order to support arbitrary frameworks allow user to provide a regex expression and search entirety of the solution?
### Never freezes
The freezing is incredibly infrequent at this point. Its something I've been improving with time. The issue stems from my understanding of the 
- Blazor Synchronization context,
- Asynchronous programming
- Concurrent programming
- etc...
Any fix I've made in the past came down to those being the root of the problem.
### Polymorphic UI
The [Notifications](https://github.com/Luthetus/Luthetus.Ide/tree/main/Luthetus.Common/Source/Lib/Luthetus.Common.RazorLib/Notifications) already can change from a notification, to a [Dialog.](https://github.com/Luthetus/Luthetus.Ide/tree/main/Luthetus.Common/Source/Lib/Luthetus.Common.RazorLib/Dialogs)
If the text editor has many tabs, with each tab representing a file, then one should be able to click and drag the tab to make it into a dialog. Then, one should be able to move a dialog into a respective dropzone to pin it to that as a tab. 
### Complete Grid Functionality
The following GIF is something [I made more than a year ago](https://www.reddit.com/r/Blazor/comments/uuzcuh/progress_on_adding_operating_system_like/) (writing this on 2023-11-01).

![completeGrid](https://github.com/Luthetus/Luthetus.Ide/assets/126622094/2cd1ded4-6e42-42e3-bcc2-8e32fcabeff3)

The complete grid functionality would not look like what is shown in the GIF, but perhaps the GIF is a good illustration of what functionality I'm referring to.
### Multi-cursor
I have showcased some of multi-cursor functionality more than a year ago in a [youtube video](https://youtu.be/szrGpPitXeA?si=8BOQXLhlyyo564B_).
I scrapped the functionality because there were some bugs that needed ironing out, yet other higher priority tasks needed my attention.
### Multi-select tree view
If one is to select a directory, and a file inside that directory how does one determine what happens upon attempting to delete the selection. The true result is that you're deleting the directory. The file within it having a selection is irrelevant. I need to think of some way to do this 'reduction' of sorts to what actually is happening.

**Comment by codymullins** [comment]
Just some feedback as someone 👀 this repo until I get time to check it out more (or the v1 release), a diff editor and unit test explorer doesn't really make me feel "blocked" from using this as a main IDE. just my $0.02 😃 

keep up the great work!

**Comment by Luthetus** [comment]
See:

- #152
- #153
