### ISSUE TITLE
Copy & Paste doesnt work in Mozilla firefox

### ISSUE THREAD

**Issue by puxson** [Luthetus/Luthetus.Ide#135]
Hello, 

Im using your text editor in my application and I found that Copy & Paste doesn't work in Mozzila firefox and I would like to ask if it is planned fix or if is there any workaround for this issue ? 

Best regards
puxson

**Comment by Luthetus** [comment]
Hi,

When writing the copy and paste I found that Firefox doesn't allow one to access the clipboard with JavaScript:
https://support.mozilla.org/bm/questions/1068472

I would like to fix this issue, I need to look into it further for a solution however.

After I finish making some immutability changes to the TextEditor, I'll see if there is a workaround.

My guess, is that the Ctrl + C keymap has its own "copy" event. And that I can add an event handler to that, instead
of an "onkeydown" event.

**Comment by Luthetus** [comment]
Stale issue. The IDE needs a release version and the issues are cluttered. I want to focus on getting high priority items listed and low priority items listed.

This would aid in anyone who has interest in the Luthetus.Ide project, what the triage is looking like for v1

**Comment by Luthetus** [comment]
This has been fixed
