### ISSUE TITLE
PlatformNotSupportedException

### ISSUE THREAD

**Issue by mxmissile** [Luthetus/Luthetus.Ide#138]
Tried running the included Hello World project, getting this when executing (hitting the play button):

`ERROR: System.PlatformNotSupportedException: Process_PlatformNotSupported at System.Diagnostics.ProcessStartInfo..ctor() at CliWrap.Command.CreateStartInfo() at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) at CliWrap.EventStream.EventStreamCommandExtensions.<>c__DisplayClass4_0.<Observe>b__0(IObserver`1 observer) at CliWrap.Utils.<Observable>F9A56BC066C1C55331A426EEC55B608B3C789C113870FC381D9D496607E7DCF71__Observable`1[[CliWrap.EventStream.CommandEvent, CliWrap, Version=3.6.4.0, Culture=neutral, PublicKeyToken=1c4a4fc2d6886e5a]].Subscribe(IObserver`1 observer) at System.Reactive.Linq.QueryLanguage.ForEachAsync_[CommandEvent](IObservable`1 , Action`1 , CancellationToken ) --- End of stack trace from previous location --- at Luthetus.Ide.RazorLib.Terminals.Models.TerminalSession.<>c__DisplayClass33_0.<<EnqueueCommandAsync>b__0>d.MoveNext()`

Windows 10, Google Chrome 120

**Comment by Luthetus** [comment]
Hi, the demo in the web browser is not fully featured. More specifically, anything relating to the terminal will not work.

You may find some terminal based tasks were implemented by me hardcoding for a specific output. But most do nothing more than throw an exception.

If one clones the repository, and runs [Luthetus.Ide.Photino.csproj](https://github.com/Luthetus/Luthetus.Ide/blob/main/Luthetus.Ide/Source/Host/Luthetus.Ide.Photino/Luthetus.Ide.Photino.csproj) natively, then the code can be ran.
