### ISSUE TITLE
Bring Cursor into View

### ISSUE THREAD

**Issue by Herdubreid** [Luthetus/Luthetus.Ide#159]
With the cursor on the last line in the editor (Lines: 16), press enter to add new line.
![image](https://github.com/Luthetus/Luthetus.Ide/assets/21098321/4519e1f8-e1bd-48aa-84bd-790b6041c62b)

A new line is added out of view (Lines: 17).  The scrollbar must be moved to bring the new line into view.
![image](https://github.com/Luthetus/Luthetus.Ide/assets/21098321/04727f2f-74ad-4a19-ba6f-057c03991831)

Impressive work by the way!

**Comment by Luthetus** [comment]
This has been fixed
